# ServerSee 配置文件

# API 服务器端口
api-port: 8080

# API 速率限制 (每分钟允许的新连接数)
# 如果你有很多服务器或者轮询间隔很短，请调高此值
api-rate-limit: 600

# 是否启用详细日志
debug: false

# 性能数据采集间隔 (秒)
collection-interval: 60

# 是否在 API 中输出插件列表
show-plugins: false

# 重启服务器时执行的命令 (默认为 spigot 的 restart 命令)
restart-command: "restart"

# 控制台日志同步设置
# 初始同步的历史日志行数
log-history-lines: 50
